version: '3.8'

services:
  # O SERVIDOR (Receptor)
  receptor-service:
    build: ./servidor
    container_name: servidor_udp
    ports:
      - "5000:5000/udp" # Mapeia a porta UDP para o host se quiser testar fora

  # O SENSOR (Emissor)
  sensor-service:
    build: ./sensor
    container_name: sensor_udp
    depends_on:
      - receptor-service