
# ── Stage 1: build ────────────────────────────────────────────────────────────
FROM golang:1.22-alpine AS builder
 
WORKDIR /app
COPY main.go .
RUN CGO_ENABLED=0 GOOS=linux go build -o sensor_temperatura .
 
# ── Stage 2: imagem mínima ────────────────────────────────────────────────────
FROM scratch
 
COPY --from=builder /app/sensor_temperatura /sensor_temperatura
 
ENTRYPOINT ["/sensor_temperatura"]
 